#!/bin/bash

#init up
VERSION=${1:-`date +%Y-%m-%d`}
TO_DIR="reprap-gen3-firmware-$VERSION"

#directory structure
echo "Exporting files..."
svn export Sanguino3G "$TO_DIR"
mv "$TO_DIR/SanguinoMaster/Configuration.h.dist" "$TO_DIR/SanguinoMaster/Configuration.h"
mv "$TO_DIR/ArduinoSlaveExtruder/Configuration.h.dist" "$TO_DIR/ArduinoSlaveExtruder/Configuration.h"

#create our archive
echo "Archiving..."
zip -qr "$TO_DIR.zip" "$TO_DIR"

#cleanup
#rm -rf $TO_DIR

#done!
echo "Release v$VERSION created as ${TO_DIR}.zip"
